Add custom title and icon (and a random surprise)
MinecraftModDevelopmentMods/CommunityMod pull request #58
Opened 2019-04-01 15:44 UTC by ErdbeerbaerLP

![image](https://user-images.githubusercontent.com/27149563/55340811-bd133380-54a5-11e9-9a57-ba99fa008eb7.png)

2019-04-01 17:15 UTC, Selim042 commented
Why crash the game intentionally?

2019-04-01 17:16 UTC, ErdbeerbaerLP commented
Just for fun, it has a 0.1% chance, I maybe add Config file for it

2019-04-01 17:17 UTC, antoinegag commented
I think we should avoid anything that crash the game on purpose. It's just obnoxious for players and not really fun.

Fake crashes would be funny tho!

2019-04-01 17:18 UTC, ErdbeerbaerLP commented
How to make those fake crashes? I later want to make bluescreen item making fake bsod.

2019-04-01 17:23 UTC, LegendaryGeek commented
If you want to fake a bsod, make shure to force mc into windowed so people dont worry as much

2019-04-01 17:38 UTC, antoinegag requested changes

2019-04-01 17:38 UTC, antoinegag commented on src/main/java/com/mcmoddev/communitymod/erdbeerbaerlp/RandomCrashes.java
> +				someCrashingMethod();
Sub mods should not crash the game on purpose

2019-04-01 17:39 UTC, ErdbeerbaerLP commented
I remove it soon (~30-50 minutes)

2019-04-01 18:26 UTC, ErdbeerbaerLP commented
Removed crashing code

2019-04-02 13:27 UTC, ProxyNeko commented
This formatting of code makes me hurt bad... Please clean it up a little xD

2019-04-02 13:50 UTC, ErdbeerbaerLP commented
Will do, currently working on something and that will clean up a little too

2019-04-02 14:20 UTC, JamiesWhiteShirt commented
Preface: Core mod contributions are allowed in my book, but they must abide by the rules and be reviewable.

All this ASM and its surrounding formatting is an unreadable mess which I will not review. It is practically obfuscated.

I am rejecting this for multiple reasons, but the primary one is this principle: A mod should not try to disguise the game as something it is not. We are modding the game, and the game's title stays. If "Minecraft" was still in the title I could have accepted it, but there are still a number of other issues.

2019-04-02 14:20 UTC, closed without merging

2019-04-02 14:25 UTC, ErdbeerbaerLP commented
I still have the ability to change the title to say Minecraft instead of MMD Community Mod

2019-04-02 14:29 UTC, JamiesWhiteShirt commented
If you can do it in a readable fashion, open a new PR with whatever it self.

2019-04-02 14:42 UTC, ErdbeerbaerLP commented
Is commenting what it does enough or do I need to redirect code execution?